name: AdminUI
main: SilverzPlayz\AdminUI\Main
version: 1.0.1
api: 3.6.0
author: esh123unicorn
commands:
  admin:
    default: op
    permission: adminui.command
    description: UI with admin commands
    aliases: ["adminui"]
